//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTVideoData_v1.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class episode
    {
        public int episodeId { get; set; }
        public int victimId { get; set; }
        public string name { get; set; }
        public string groupName { get; set; }
        public string episodeHref { get; set; }
        public string backupHref { get; set; }
        public string alias { get; set; }
    
        public virtual victim victim { get; set; }
    }
}
