//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTVideoData_v1.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class keyword
    {
        public int keyWordId { get; set; }
        public Nullable<int> movieId { get; set; }
        public string keyWords { get; set; }
    
        public virtual movie movie { get; set; }
    }
}
