//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTVideoData_v1.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NTVideoEntities : DbContext
    {
        public NTVideoEntities()
            : base("name=NTVideoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<actor> actors { get; set; }
        public DbSet<category> categories { get; set; }
        public DbSet<comment> comments { get; set; }
        public DbSet<country> countries { get; set; }
        public DbSet<director> directors { get; set; }
        public DbSet<download> downloads { get; set; }
        public DbSet<episode> episodes { get; set; }
        public DbSet<keyword> keywords { get; set; }
        public DbSet<movie> movies { get; set; }
        public DbSet<trailer> trailers { get; set; }
        public DbSet<upload> uploads { get; set; }
        public DbSet<victim> victims { get; set; }
        public DbSet<home_page_position> home_page_position { get; set; }
        public DbSet<episode_need_update_to_live> episode_need_update_to_live { get; set; }
    }
}
