//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTVideoData_v1.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class movie
    {
        public movie()
        {
            this.keywords = new HashSet<keyword>();
            this.victims = new HashSet<victim>();
            this.actors = new HashSet<actor>();
            this.categories = new HashSet<category>();
            this.countries = new HashSet<country>();
            this.directors = new HashSet<director>();
            this.home_page_position = new HashSet<home_page_position>();
        }
    
        public int movieId { get; set; }
        public string name1 { get; set; }
        public string name2 { get; set; }
        public string alias { get; set; }
        public Nullable<int> isMultiEpisode { get; set; }
        public Nullable<System.DateTime> dateUpdate { get; set; }
        public string name1CheckField { get; set; }
        public string name2CheckField { get; set; }
        public Nullable<int> publishYear { get; set; }
        public Nullable<int> isPublic { get; set; }
    
        public virtual ICollection<keyword> keywords { get; set; }
        public virtual ICollection<victim> victims { get; set; }
        public virtual ICollection<actor> actors { get; set; }
        public virtual ICollection<category> categories { get; set; }
        public virtual ICollection<country> countries { get; set; }
        public virtual ICollection<director> directors { get; set; }
        public virtual ICollection<home_page_position> home_page_position { get; set; }
    }
}
