//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTVideoData_v1.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class upload
    {
        public int uploadId { get; set; }
        public Nullable<int> victimId { get; set; }
        public string name { get; set; }
        public string uploadPath { get; set; }
        public string status { get; set; }
        public string server { get; set; }
    
        public virtual victim victim { get; set; }
    }
}
