//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTVideoData_v1.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class victim
    {
        public victim()
        {
            this.comments = new HashSet<comment>();
            this.downloads = new HashSet<download>();
            this.episodes = new HashSet<episode>();
            this.trailers = new HashSet<trailer>();
            this.uploads = new HashSet<upload>();
            this.episode_need_update_to_live = new HashSet<episode_need_update_to_live>();
        }
    
        public int victimId { get; set; }
        public Nullable<int> movieId { get; set; }
        public string name { get; set; }
        public Nullable<int> isDefault { get; set; }
        public string movieHref { get; set; }
        public string thumb { get; set; }
        public string poster { get; set; }
        public string description { get; set; }
        public Nullable<int> totalEpisode { get; set; }
        public Nullable<int> currentEpisode { get; set; }
        public string duration { get; set; }
        public string quality { get; set; }
        public Nullable<int> hasSub { get; set; }
        public Nullable<int> hasDubbing { get; set; }
        public Nullable<int> hasTrans { get; set; }
        public string movieDetailHref { get; set; }
        public Nullable<int> isContinue { get; set; }
        public Nullable<System.DateTime> dateUpdate { get; set; }
        public Nullable<int> updateState { get; set; }
        public Nullable<int> viewed { get; set; }
        public Nullable<double> rating { get; set; }
        public string schedule { get; set; }
        public string smallImage { get; set; }
        public Nullable<int> victimTypeNo { get; set; }
        public string downloadStatus { get; set; }
        public string uploadStatus { get; set; }
        public Nullable<int> priority { get; set; }
        public Nullable<int> isTrailer { get; set; }
        [MaxLength]
        public string playListHtml { get; set; }
        [MaxLength]
        public string playListHtmlBk { get; set; }
    
        public virtual ICollection<comment> comments { get; set; }
        public virtual ICollection<download> downloads { get; set; }
        public virtual ICollection<episode> episodes { get; set; }
        public virtual movie movie { get; set; }
        public virtual ICollection<trailer> trailers { get; set; }
        public virtual ICollection<upload> uploads { get; set; }
        public virtual ICollection<episode_need_update_to_live> episode_need_update_to_live { get; set; }
    }
}
